version: '3.3'
services:
  api:
    image: 'unreal-logistics-api:latest'
    container_name: api
    env_file:
      - .env
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./data:/data
