name: Docker Image CI

on:
  push:
  pull_request:
    
permissions:
  contents: write  
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.201'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: RunNuke Compile
        run: ./build.sh BuildDockerImage --ActiveProject Api